//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YOY.DAO {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=de4tg5joydev.database.windows.net,1433;Initial Catalog=yoyIj7qM58dCj;" +
            "MultipleActiveResultSets=true;Persist Security Info=True;User ID=yoyadmi3726;Pas" +
            "sword=vCRUS4JypY0yzFjry5hb")]
        public string default_connection {
            get {
                return ((string)(this["default_connection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"BQXtvmvwRg4DVQCm5I6Wt+kNIlezwES8lfbiZoB0DBIfkSZu8Ft3e31jYHNdyfydmpRWO978kfc8UxbtFbfV7E9Af3n+nFSjV+MygcCT7mxxgKH0FB4wrGNDpcVyle6yiRxbcaaZdzhAtfhFkX8qlXigG3JURWIwPvrNeMQGSRuqgO0N1b/G8TS43VZhqVr/O0pDrGDtZlIqoIvcwa1Dv8isYSfL++bWCw0SffMHiLdFuIG9E8u7mPJU0GoUs13UUPTphKPkkHrwD4ds6ncCnGMRejHjZIPKTyq1Rf1zj1jxp9d/1eLs+rRTsMrQ/g7P+NlkiPpJDYZoLNBuveCnWQ==")]
        public string salt {
            get {
                return ((string)(this["salt"]));
            }
        }
    }
}
