//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YOY.ThirdpartyServices {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("azure_66180f966b172f8e44ae5436c2afb20e@azure.com\r\n")]
        public string sendgrid_username {
            get {
                return ((string)(this["sendgrid_username"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yTXri14u121uEuk\r\n")]
        public string sendgrid_password {
            get {
                return ((string)(this["sendgrid_password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("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")]
        public string sendgrid_apikey {
            get {
                return ((string)(this["sendgrid_apikey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("audiostorage@enjoyit-961.iam.gserviceaccount.com")]
        public string drive_service_account {
            get {
                return ((string)(this["drive_service_account"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yoyimgs")]
        public string cloudinaryCloudName {
            get {
                return ((string)(this["cloudinaryCloudName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("427598412712759")]
        public string cloudinaryApiKey {
            get {
                return ((string)(this["cloudinaryApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EpNpUUQVtrZg5JC5_D3NsvmrDBc")]
        public string cloudinaryApiSecret {
            get {
                return ((string)(this["cloudinaryApiSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6d59677373947956772bffedd94abe41")]
        public string algoliaApiKey {
            get {
                return ((string)(this["algoliaApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("925fa4aabca0414280fa6c083dce4652")]
        public string cognitiveServicesSubscriptionKey {
            get {
                return ((string)(this["cognitiveServicesSubscriptionKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://southcentralus.api.cognitive.microsoft.com/vision/v2.0/ocr")]
        public string visionOCRServicesUriBase {
            get {
                return ((string)(this["visionOCRServicesUriBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("676417410513")]
        public string fcmSenderId {
            get {
                return ((string)(this["fcmSenderId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAAAnX2eldE:APA91bHwieXy17-ahCvRi0lDmfTwVKQzr9YGNv5QBqyRvSJ6lv0vlgX19zJlFVmUHwG5m" +
            "lEwyib-rLilqGiycIezHZhYRMZi8ISGzUcZ01e4JOP3w8GiT0hhMX05cSQ6VJM1pY3t59wF")]
        public string fcmApiKey {
            get {
                return ((string)(this["fcmApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACdac490f123cf29dff800cfca9ce76734")]
        public string twilioAccountSID {
            get {
                return ((string)(this["twilioAccountSID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d5367d843c0180d634dbf222244d39a5")]
        public string twilioAuthToken {
            get {
                return ((string)(this["twilioAuthToken"]));
            }
        }
    }
}
